export const NAVIGATE_NEXT_PAGE = 'NAVIGATE_NEXT_PAGE'

export const FETCH_ADS_ERROR = 'FETCH_ADS_ERROR';
export const FETCH_ADS_REQUEST = 'FETCH_ADS_REQUEST'
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS'

export const FETCH_AD_DETAIL_ERROR = 'FETCH_AD_DETAIL_ERROR';
export const FETCH_AD_DETAIL_REQUEST = 'FETCH_AD_DETAIL_REQUEST'
export const FETCH_AD_DETAIL_SUCCESS = 'FETCH_AD_DETAIL_SUCCESS'